7th-UMC-Hackathon-TeamV/client

README.md

docs: 리드미에 컨벤션 작성

---

src/App.js
src/pages/HomePage/HomePage.jsx
src/pages/HomePage/HomePage.style.jsx
src/pages/HomePage/index.js
src/pages/LoginPage/LoginPage.jsx
src/pages/LoginPage/LoginPage.style.jsx
src/pages/LoginPage/index.js
src/pages/NewsPage/NewsPage.jsx
src/pages/NewsPage/NewsPage.style.jsx
src/pages/NewsPage/index.js
src/pages/index.js
src/router.jsx

- 기본 페이지 세팅 (홈, 로그인, 뉴스 페이지)
<br />

feat: 기본 페이지 세팅

---

src/App.js
src/styles/GlobalStyle.style.jsx
src/styles/PretendardFont.style.jsx
src/styles/ResetStyles.style.jsx
src/styles/index.js
src/styles/onAirStyles.style.jsx

feat: 폰트 및 글로벌 스타일 적용

---

src/App.css

feat: 모바일 너비 사이즈 지정

---

src/styles/onAirStyles.style.jsx

feat: 폰트를 변수로 지정

---

src/components/BottomBar/BottomBar.jsx
src/components/BottomBar/BottomBar.style.jsx
src/components/BottomBar/index.js
src/components/PageLayout/PageLayout.jsx
src/components/PageLayout/PageLayout.style.jsx
src/components/index.js
src/pages/HomePage/HomePage.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/NewsPage/NewsPage.jsx

- bottom bar 위치 변경 및 적용
<br />

modify: bottom bar 위치 변경 및 적용

---

src/components/NewsAlertBox/NewsAlertBox.jsx
src/components/NewsAlertBox/NewsAlertBox.style.jsx
src/components/NewsAlertBox/index.js
src/components/index.js
src/pages/HomePage/HomePage.jsx
src/pages/HomePage/HomePage.style.jsx

- news alert box 구현
- 구현 화면
<br />

feat: news alert box 구현

---

src/components/NewsHeader/NewsHeader.jsx
src/components/NewsHeader/NewsHeader.style.jsx
src/components/NewsHeader/index.js
src/pages/HomePage/HomePage.jsx
src/pages/HomePage/HomePage.style.jsx

feat: 뉴스 헤더 컴포넌트 생성

---

public/svgs/icon-active-check-box.svg
public/svgs/icon-inactive-check-box.svg
src/components/BottomBar/BottomBar.jsx
src/pages/HomePage/HomePage.style.jsx
src/pages/UpdateNewsPage/UpdateNewsPage.jsx
src/pages/UpdateNewsPage/UpdateNewsPage.style.jsx
src/pages/UpdateNewsPage/index.js
src/pages/index.js
src/router.jsx
src/styles/onAirStyles.style.jsx

feat: 뉴스 생성 페이지 구현

---

src/pages/LoginPage/LoginPage.style.jsx

fix: 로그인 UI 수정

---

package.json
src/pages/StartPage/StartPage.jsx
src/pages/StartPage/StartPage.style.js
src/router.jsx

close #28 
<br />
-링크 생성 페이지 제작 및 페이지 라우팅 순서 수정
<br />

feat: 링크 생성 페이지 제작

---

src/pages/LoginPage/LoginPage.jsx
src/pages/LoginPage/LoginPage.style.jsx

close #43
<br />
- 로그인 타이틀에 컴포넌트 적용
<br />

feat: 로그인 타이틀에 컴포넌트 적용

---

src/components/NewsHeader/NewsHeader.style.jsx
src/pages/HomePage/HomePage.style.jsx

close #48 
<br />
- 홈 화면 컴포넌트 간격 수정
<br />

chore: 홈 화면 컴포넌트 간격 수정

---

src/pages/LoginPage/LoginPage.jsx
src/router.jsx

close #50
<br />
- 전체 페이지 동적 라우팅 적용
<br />

feat: dynamic-routing

---

src/pages/HomePage/HomePage.jsx
src/pages/HomePage/HomePage.style.jsx
src/pages/LoginPage/LoginPage.jsx

close #52
<br />
- 홈화면 내 일부 컴포넌트 삭제 및 추가
<br />

feat: 홈화면 내 일부 컴포넌트 삭제 및 추가

---

src/components/BottomBar/BottomBar.jsx

close #53
<br />
- BottomBar의 navigator url 수정
<br />

feat: bottombar-routing

---

src/components/NewsCardList/NewsCardList.jsx
src/pages/HomePage/HomePage.jsx

close #69
<br />
- 뉴스 사진 mock data 추가
<br />

chore: 뉴스 사진 mock data 추가

---

src/components/BottomBar/BottomBar.style.jsx
src/pages/LoginPage/LoginPage.style.jsx
src/pages/StartPage/StartPage.jsx
src/pages/StartPage/StartPage.style.js

close #66
<br />
- ui 일부 수정
<br />

modify: ui 일부 수정

---

src/components/BottomBar/BottomBar.jsx
src/components/BottomBar/BottomBar.style.jsx
src/components/HotNewsCard/HotNewsCard.jsx
src/components/NewsCard/NewsCard.jsx
src/pages/NewsPage/NewsPage.jsx
src/pages/NewsPage/NewsPage.style.jsx

close #68
<br />
- 뉴스 상세 페이지 라우팅
- style 수정
<br />

feat: add-card-routing

---

src/pages/StartPage/StartPage.style.js

close #73
<br />
- 버튼 너비 수정
<br />

fix: 버튼 너비 수정

---

src/components/HotNewsCard/HotNewsCard.style.jsx
src/components/NewsCard/NewsCard.style.jsx
src/pages/NewsPage/NewsPage.jsx
src/pages/NewsPage/NewsPage.style.jsx

close #77
<br />
- 상세페이지 수정
<br />

chore: 상세 페이지 수정

---

src/pages/LoginPage/LoginPage.jsx

close #79
<br />
- 로그인 UI 수정
<br />

feat: modify-login

---

src/components/NewsCard/NewsCard.style.jsx
src/pages/MyPage/MyPage.jsx

close #81
<br />
- 마이페이지 더미데이터 카드 생성
<br />

chore: 마이페이지 더미데이터 카드 생성

---

src/pages/MyPage/MyPage.jsx

close #83
<br />
- 마이페이지 style 수정
<br />

fix: modify-mypage-style

---

src/pages/StartPage/StartPage.jsx

close #64
<br />
- 그룹 생성 API 연동
<br />

feat: connect-group-api

---

src/components/HotNewsCard/HotNewsCard.style.jsx
src/components/NewsCard/NewsCard.style.jsx
src/pages/HomePage/HomePage.jsx

close #87
<br />
- 속보 뉴스 디자인 수정
<br />

chore: 속보 뉴스 디자인 수정
